import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const SOURCE = process.env.OPENAPI_SOURCE ?? '../araguaney_back/openapi.json';
const OUT = resolve(process.cwd(), 'types/openapi.d.ts');

async function main() {
  const isUrl = SOURCE.startsWith('http://') || SOURCE.startsWith('https://');
  const input = isUrl ? new URL(SOURCE) : resolve(process.cwd(), SOURCE);
  if (!isUrl && !existsSync(input as string)) {
    throw new Error(
      `OpenAPI source not found at ${input}. Set OPENAPI_SOURCE env var or place the file.`,
    );
  }
  const ast = await openapiTS(input);
  const ts = astToString(ast);
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `// AUTOGENERATED — do not edit. Run \`pnpm types:generate\`.\n${ts}`, 'utf8');
  console.log(`OpenAPI types written to ${OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
